-- Compatibility marker for the legacy cloud-sync SQL.
-- The old version created permissive policies and was never recorded in the
-- linked project's migration history. Schema creation, RLS, and the trigger
-- now live in 0005_repair_player_rls.sql, so this migration is intentionally
-- empty and only closes the local/remote history gap.;
